name: e2e-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: dbea81c2-9e90-440e-9ee1-25c40030a1c5
