
name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Run tests then artifact the test results
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
          
      - name: start uat
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
            
      - name: Checkout - Clone the repository master branch
        uses: actions/checkout@v3

      - name: Run the testcases
        uses: cypress-io/github-action@v5
        with:
            command: npx cypress run
